server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/registration_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: mail.rashkemsoft.com.ng
    port: 587
    username: admin@rashkemsoft.com.ng
    password: admin4rashkem
    properties:
      mail:
        smtp:
          auth: true
          starttls:
             enable: true
