
name: Build & Deploy Spring app

on:
  push:
    branches:
      - main


jobs:
  build-deploy:
    name: Build and Deploy Spring boot
    runs-on: Ubuntu-latest
    steps:
      - name: Checkout@v3
        uses: actions/checkout@v3

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 21

      - name: Unit Tests
        run: mvn -B test --file pom.xml mvn clean install -Dmaven.test.skip=true

      - name: Build the application
        run:
          mvn clean
          mvn -B package --pom.xml

